#
# Package name and list of source files.
#

NAME=R2Spaces
CCSRCS=$(NAME).cpp \
    R2Wing.cpp \
    R2Bspt.cpp \
    R2Spct.cpp \
    R2Sbeam.cpp R2Pbeam.cpp R2Beam.cpp \
    R2Space.cpp \
    RNWing.cpp RNTree.cpp RNList.cpp RNAdt.cpp



#
# Compile flags
#

USER_CFLAGS=-w



#
# R3 library makefile
#

include ../../makefiles/Makefile.pkgs








